spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: ${SPRING_SECURITY_NAME:}
      password: ${SPRING_SECURITY_PASSWORD:}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}

server:
  port: 8080
  servlet:
    context-path: /api
jwt:
  signerKey : ${JWT_SIGNER_KEY:}
  valid-duration: ${JWT_VALID_DURATION:}
  refreshable-duration: ${JWT_REFRESH:}

cloudinary:
  name: ${CLOUDINARY_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}

open_cage:
  api-key: ${OPEN_CAGE_API_KEY:}
